### ISSUE TITLE
Kext not unloading and PCI-E speed still at 2.5 GT/s

### ISSUE THREAD

**Issue by Piffol** [matatata/lnkspd#1]
Hi,

just wondering if you might know what the issue is that I'm experiencing using the code?
The kext is not unloading - and the speed link speed on the pci-e card NVME is till only at 2.5 gt/s per band even though indicates upgrade - as below.
I'm also keen to do the same to slot 1 (graphics card) and have tried all of the slot numbers related to to the x16 slot in the list that generated - but that's sticking at PCI. Im wondering if thats because the kext needs to successfully unload - before you run again on another slot?
Thanks in advance,
Piffol

/usr/local/share/DirectHW.kext loaded successfully (or already loaded).
dom:bus:slot.f		Vendor	Device	Speed	Width	Name | Vendor		
0000:00:01.0		8086	4021	PCIe2.0	4x	Device 4021 | Vendor 8086
nothing to do, link speed is 2 already
(kernel) Can't remove kext com.apple.driver.DirectHW; services failed to terminate - 0xe00002c7.
Failed to unload com.apple.driver.DirectHW - (iokit/common) unsupported function.

**Comment by matatata** [comment]
Hi Piffol,

I'm sorry that I did not react earlier. To be honest I simply missed it as I was very inactive on github lately. However I'm afraid I cannot really help. It did work with my MacPro3,1 and my NVME card, but I'm not using it anymore. Maybe I was just lucky. DirectHW.kext is required so that the pciutils library can access the memory areas. I don't know why the kext cannot be unloaded. Maybe it's a sign that the kext is not working properly. Maybe if you build everything yourself with the latest Xcode for the current macOS? I don't remember if I had it running on Mojave or already Catalina. In any case the SIP protection must be turned off otherwise the kext won't load anyway, but seems you know and did that already.

My solution was based on something someone posted on macrumours.com. It basically also used DirectHW.kext and a build of pciutils and a shell script calling pciutil. My solution does the same but directly calls the pciutil library. I've found the files and attached them here. Maybe it helps.

Best regards,
Matatata
[PCIe2.zip](https://github.com/matatata/lnkspd/files/6524666/PCIe2.zip)
